In [8]:
import numpy as np
import pandas as pd
import sys
import json

def get_data(data_file):
#     print("analyzing given file...")
    
    states = []
    recovered = []
    deaths = []
    hospitalized = []
    totalTestResults = []
    total = []


    try:
        f = open(data_file)
        data = json.load(f)
    except:
        print("Error in retrieving file")
        exit()


    for n in data:
        params = (n['state'],n['recovered'],n['death'],n['hospitalized'],n['totalTestResults'],n['total'])
        states.append(0 if params[0] == None else params[0])
        recovered.append(0 if params[1] == None else params[1])
        deaths.append(0 if params[2] == None else params[2])
        hospitalized.append(0 if params[3] == None else params[3])
        totalTestResults.append(0 if params[4] == None else params[4])
        total.append(0 if params[5] == None else params[5])
    f.close()
    
#     print(states)
#     print(recovered)
#     print(deaths)
#     print(hospitalized)
#     print(totalTestResults)
#     print(total)

    df = pd.DataFrame({'recovered':recovered,
                       'deaths':deaths,
                       'hospitalized':hospitalized,
                       'totalTestResults':totalTestResults,
                       'total':total})
    df.index = states
    return df

In [19]:
!ls

4-13-2020-Current-State-Covid19-data.json
4-20-2020-covid19.json
4-28-2020-covid19.json
Untitled.ipynb
plot-data.py

In [16]:
df1 = get_data('4-13-2020-Current-State-Covid19-data.json')
df2 = get_data('4-20-2020-covid19.json')
df3 = get_data('4-28-2020-covid19.json')
# df1.sort_values(by="deaths",ascending=False)

    recovered  deaths  hospitalized  totalTestResults   total
NY      23887    9385         42594            461601  461601
NJ          0    2350             0            126735  126735
MI        433    1487             0             79437   79437
LA          0     840             0            104045  104045
MA          0     756          2235            116730  116730
IL          0     720             0            100735  100735
CA          0     651             0            190328  203528
CT          0     554             0             41220   41220
WA          0     508             0             93802   93802
PA          0     507             0            124890  124890
FL          0     474          2811            184926  186193
GA          0     442          2518             54551   54551
IN          0     343             0             42489   42489
CO          0     290          1417             37153   37153
TX       2014     271             0            124533  124533
MD        603     262          1975             51751   51751
OH          0     253          1948             63243   63243
VA          0     149             0             41401   41874
WI          0     144           974             39257   39257
AZ          0     115             0             42109   42109
NV          0     114             0             24611   24611
MO          0     110             0             45200   45200
TN       1504     101           567             70677   70677
KY        607      97           667             25866   25866
MS          0      96           548             21413   21413
OK        865      96           446             22760   22760
AL          0      95           437             21669   21669
SC          0      82           496             31425   31425
NC          0      81             0             62139   62139
MN        842      70           361             37421   37421
RI         35      63             0             20350   20350
KS          0      56           298             13253   13253
DC        507      52             0             10934   10934
OR          0      52           359             29758   29758
PR          0      45             0              6863    8151
IA        674      41             0             17592   17592
DE        213      35             0             11820   11820
VT         15      28             0             10365   10365
ID          0      27           132             14881   14881
AR        367      27           130             19722   19722
NM        295      26             0             30515   30515
NH        239      23           152             11207   11332
ME        266      19           120              6721    6721
UT          0      18           195             44234   44234
NE          0      17             0             10972   10972
HI        310       9            44             18844   18844
WV         83       8             0             16257   16257
AK         66       8            31              8038    8038
ND        121       8            39             10350   10350
SD        197       6            43              8553    8553
MT        169       6            47              8913    8913
GU         58       5             0               905     905
MP          0       2             0                38      47
VI         43       1             0               373     375
WY        138       0            41              5571    5571
AS          0       0             0                 3       5

In [18]:
print("Changes from April 13 to April 20 2020")
delta = df2-df1
# delta.sort_values(by="recovered",ascending=False)
delta.sort_values(by="deaths",ascending=False)
# delta.sort_values(by="hospitalized",ascending=False)
# delta.sort_values(by="totalTestResults",ascending=False)
# delta.sort_values(by="total",ascending=False)

Changes from April 13 to April 20 2020

    recovered  deaths  hospitalized  totalTestResults   total
NY          0    4962         14509            172260  172260
NJ          0    2027             0             51322   51322
MI       2804     981             0             34361   34361
MA          0     950         -2235             45511   45511
CT          0     777             0             21586   21586
PA          0     697             0             38062   38062
IL          0     629             0             47623   47623
CA          0     557             0            100172   86972
LA          0     488             0             38054   38054
FL          0     332          1199             81299   81136
GA          0     291          1032             29777   29777
OH          0     256           705             27193   27193
MD        314     254          1039             19646   19646
IN          0     226             0             22150   22150
TX       3692     224             0             65861   65861
VA       1324     151          1500             15334   15329
CO          0     132           396              9042    9042
WA          0     126             0             44840   44840
NC          0      98             0             17345   17345
RI        232      92           331             16730   16730
WI          0      86           237             11845   12082
MS          0      73           271             30021   30021
MN        360      73           241              9429    9429
AL          0      72           204             24231   24231
AZ       1155      72             0             12391   12391
MO          0      67             0             10813   10813
DC        123      53             0              3179    3179
KY        567      51           392              6706    6706
TN       2071      51           163             30012   30012
OK        749      47            95             12886   12886
NV          0      44             0              7736    7736
KS          0      44           107              5508    5508
IA        561      38             0              8228    8228
SC       2063      38           280              9055    9055
DE        282      37             0              4650    4650
NM        192      29           274              6527    6527
OR          0      23           106             10287   10287
NH        282      18            46              2911    3084
ID        585      18            19              2564    2564
PR          0      18             0              2875    3482
WV        207      16             0              5898    5898
ME        148      16            18              8230    8230
AR        382      15           161              6831    6831
NE          0      11             0              4708    4708
VT          0      10             0              2616    2616
UT        776      10            73             24077   24077
ND         68       5            14              4397    4397
MT         74       4            10              2138    2138
WY         95       2            10              1815    1815
VI          5       2             0               234     250
SD        512       1            44              3773    3773
HI        104       1             8              5331    5331
AK         95       1             5              2086    2086
AS          0       0             0                 0      15
GU         54       0             0               219     219
MP         11       0             0                27      18

In [19]:
print("Changes from April 20 to April 28 2020")
delta = df3-df2
# delta.sort_values(by="recovered",ascending=False)
delta.sort_values(by="deaths",ascending=False)
# delta.sort_values(by="hospitalized",ascending=False)
# delta.sort_values(by="totalTestResults",ascending=False)
# delta.sort_values(by="total",ascending=False)

Changes from April 20 to April 28 2020

    recovered  deaths  hospitalized  totalTestResults  total
AK          0       0             0                 0      0
AL          0       0             0                 0      0
NH          0       0             0                 0      0
NJ          0       0             0                 0      0
NM          0       0             0                 0      0
NV          0       0             0                 0      0
NY          0       0             0                 0      0
OH          0       0             0                 0      0
OK          0       0             0                 0      0
OR          0       0             0                 0      0
PA          0       0             0                 0      0
RI          0       0             0                 0      0
SC          0       0             0                 0      0
SD          0       0             0                 0      0
TN          0       0             0                 0      0
TX          0       0             0                 0      0
UT          0       0             0                 0      0
VA          0       0             0                 0      0
VT          0       0             0                 0      0
WA          0       0             0                 0      0
WI          0       0             0                 0      0
WV          0       0             0                 0      0
WY          0       0             0                 0      0
PR          0       0             0                 0      0
AS          0       0             0                 0      0
GU          0       0             0                 0      0
MP          0       0             0                 0      0
NE          0       0             0                 0      0
ND          0       0             0                 0      0
NC          0       0             0                 0      0
ID          0       0             0                 0      0
AR          0       0             0                 0      0
AZ          0       0             0                 0      0
CA          0       0             0                 0      0
CO          0       0             0                 0      0
CT          0       0             0                 0      0
DC          0       0             0                 0      0
DE          0       0             0                 0      0
FL          0       0             0                 0      0
GA          0       0             0                 0      0
HI          0       0             0                 0      0
IA          0       0             0                 0      0
IL          0       0             0                 0      0
MT          0       0             0                 0      0
IN          0       0             0                 0      0
KS          0       0             0                 0      0
KY          0       0             0                 0      0
LA          0       0             0                 0      0
MA          0       0             0                 0      0
MD          0       0             0                 0      0
ME          0       0             0                 0      0
MI          0       0             0                 0      0
MN          0       0             0                 0      0
MO          0       0             0                 0      0
MS          0       0             0                 0      0
VI          0       0             0                 0      0